Budstudio 9 DCM/API added
BudEcosystem/Bud-Studio-API pull request #13
Opened 2023-04-27 11:11 UTC by prakaccubits123

2023-04-28 03:56 UTC, sonalidevbud requested changes
Good work on sorting with eslint!

2023-04-28 03:56 UTC, sonalidevbud commented on src/routes/v1/workspace.route.ts
> +  .route('/duplicate/:workspaceId')
Let's have routes as
/:workspaceId/duplicate 
/:workspaceId/copy -> destWorkspace take inside req body
/:workspaceId/move -> destWorkspace take inside req body

2023-04-28 03:56 UTC, sonalidevbud commented on src/routes/v1/workspace.route.ts
> +    validate(workspaceValidation.woveWorkspace),
spelling for moveWorkspace

2023-04-28 03:56 UTC, sonalidevbud commented on src/modules/workspace/workspace.service.ts
> +  if (!workspace?.isActive || !workspace.creatorId.equals(userId)) {
if workspace.isActive = false then this 'if' condition will be true and we will throw error - which is not correct flow

2023-04-28 03:56 UTC, sonalidevbud commented on src/modules/workspace/workspace.service.ts
> +  delete newWorkspace.folders;
newWorkspace.documents should also be deleted

2023-04-28 03:56 UTC, sonalidevbud commented on src/modules/workspace/workspace.service.ts
> +      if (folder && folder.creatorId.equals(userId)) {
here there's no need to check whether folder creatorId is the user accessing the workspace, because once user has right for workspace, he will automatically have right for all subsequent folders and documents

2023-04-28 03:56 UTC, sonalidevbud commented on src/modules/workspace/workspace.service.ts
> +        const folderCopy = await Folder.create(newFolder);
if we do this then we are making a copy of the folder but not making a copy of the document it contains -> there should be new function inside folder service called copy folder, which should in turn call another function in document service called documentCopy
So in the process of copying a folder, first copies of documents will be created, then copy of folder will be created - copied documents will be added to the copied folder and then this new replica will be added to newWorkspace
As you know documents can have children and parent documents - which we will handle later.

2023-04-28 03:56 UTC, sonalidevbud commented on src/modules/workspace/workspace.service.ts
> +  if (workspace.folders) {
in move you don't have to create copies - you can simply delete from current and paste in destWorkspace, workspaceId in folders and documents should be updated to destWorkspaceId

2023-04-28 03:56 UTC, sonalidevbud commented on src/modules/workspace/workspace.service.ts
> +  if (workspace.folders) {
Also while creating copy function folder service remember to pass destWorkspace details, because later we will add suffix _copy which will require copy folder to know about existing folders in the destWorkspace

2023-04-28 04:22 UTC, prakaccubits123 commented on package.json
> +    "prettier-plugin-sort-json": "^1.0.0",
yess

2023-05-01 17:52 UTC, sonalidevbud requested changes

2023-05-01 17:52 UTC, sonalidevbud commented on src/modules/folder/folder.service.ts
> +        const copiedDocumentsids = await documentService.copyDocument(folder.documents, folderCopy);
correct name copiedDocumentsids -> copiedDocumentsIds

2023-05-01 17:52 UTC, sonalidevbud commented on src/modules/document/document.service.ts
> +export const copyDocument = async (documents: any, folderOrWorkspace?: any): Promise<string[]> => {
type of documents : any -> can we be more specific - mostly it will be list of mongo object ids, right? or empty array - isn't it?

2023-05-01 17:52 UTC, sonalidevbud commented on src/modules/workspace/workspace.service.ts
> +        document.workspaceId = destWorkspaceId;
handle children documents in move

2023-05-01 17:52 UTC, sonalidevbud commented on src/modules/workspace/workspace.controller.ts
> +    new mongoose.Types.ObjectId(req.params['workspaceId']),
in order to maintain consistency - lets transform workspaceId to objectId forst and then pass to service function as done on line 61.

2023-05-02 04:24 UTC, prakaccubits123 commented on src/modules/document/document.service.ts
> +export const copyDocument = async (documents: any, folderOrWorkspace?: any): Promise<string[]> => {
yes it is list of objectid or it can be empty array.

2023-05-02 04:24 UTC, prakaccubits123 commented on src/modules/workspace/workspace.service.ts
> +        document.workspaceId = destWorkspaceId;
ohhkay

2023-05-10 05:09 UTC, closed without merging