Create document, Get all document modifications
BudEcosystem/Bud-Studio-API pull request #14
Opened 2023-04-27 13:25 UTC by vsraccubits

2023-04-27 13:37 UTC, vsraccubits commented
### Output

https://www.awesomescreenshot.com/video/16896507?key=a5caa89c6a820809bee73c0ca02db5ce

2023-04-27 13:56 UTC, sonalidevbud requested changes

2023-04-27 13:56 UTC, sonalidevbud commented on src/modules/document/document.service.ts
> +  if (folderId || (folderId && workspaceId)) {
i think we can simplify this condition
if folderId {
  if workspaceId {
       del
  }
}

2023-04-27 13:56 UTC, sonalidevbud commented on src/modules/document/document.service.ts
> +    document = await Document.create({ ...documentBodyCopy, creatorId: userId });
since we are changing multiple collections - document and folder -> we should use session, if error occurs in folder save then document will be create and it won't be added in folder collection - in this scenario we will need rollback

2023-04-27 13:56 UTC, sonalidevbud commented on src/modules/workspace/workspace.service.ts
> +  const session = await mongoose.startSession();
this functionality will change - better remove it from your PR - delete workspace api changes

2023-04-28 03:37 UTC, vsraccubits commented on src/modules/document/document.service.ts
> +    document = await Document.create({ ...documentBodyCopy, creatorId: userId });
Implemented Transactions

2023-04-28 03:38 UTC, vsraccubits commented on src/modules/workspace/workspace.service.ts
> +  const session = await mongoose.startSession();
Submitted a new pr with only contain workspace model changes

2023-04-28 03:38 UTC, vsraccubits commented on src/modules/document/document.service.ts
> +  if (folderId || (folderId && workspaceId)) {
The condition has been modified

2023-04-28 04:00 UTC, closed without merging